version: '3.9'
services:
  prism:
    build: ./dockerfile/prism
    tty: true
    volumes:
      - ./reference:/data
    ports:
      - "3010:3010"
    networks:
      - cansho_development

  redoc:
    build: ./dockerfile/redoc
    tty: true
    volumes:
      - ./reference:/data
    ports:
      - "3020:3020"
    networks:
      - cansho_development

networks:
  cansho_development:
    external: true
