openapi: 3.1.0
x-stoplight:
  id: kaj0lsq8f2jst
info:
  title: cansho-api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /login:
    post:
      summary: ログイン
      operationId: post-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                example-1:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                loginId:
                  type: string
                password:
                  type: string
            examples:
              example-1:
                value:
                  loginId: string
                  password: string
        description: ''
  /api/user:
    get:
      summary: ユーザー情報取得
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                example-2:
                  value:
                    userId: 142
                    firstName: Alice
                    lastName: Smith
      operationId: get-api-user
  /api/post:
    post:
      summary: 記事投稿
      operationId: post-posts-new
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                public:
                  type: boolean
            examples:
              example-1:
                value:
                  title: string
                  content: string
                  public: true
    parameters: []
  '/api/post/{postId}':
    parameters:
      - schema:
          type: string
        name: postId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: get-api-post-postId
  /api/image/upload:
    post:
      summary: 画像アップロード
      operationId: post-api-image-upload
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  path:
                    type: string
              examples:
                example-1:
                  value:
                    path: 'https://picsum.photos/1300/500'
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        userId:
          type: string
        firstName:
          type: string
        lastName:
          type: string
      required:
        - firstName
        - lastName
